### ISSUE TITLE
AttributeError: 'widgetuff' object has no attribute 'show3D'

### ISSUE THREAD

**Issue by nilswagner** [ladisk/uff_widget#6]
import uff_widget
uff_1=uff_widget.widgetuff('tree_structure_mini.unv')
uff_1.read_uff()
uff_1.get_info()
uff_1.show_frf()
uff_1.show3D()

**Comment by jankoslavic** [comment]
you should use `uff_1.show_3D()` not `uff_1.show3D()`

**Comment by nilswagner** [comment]
O.k. There is typo in
https://github.com/ladisk/uff_widget#viewing-geometry-and-oscilatin-in-3d

**Comment by jankoslavic** [comment]
Thanks. Corrected now:)
